/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/AddItemsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/InventoryItemsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/LabelManualEdit`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/BudgetListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/EnterBudgetScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/EditItemsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/MemberScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/AddItemsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/InventoryItemsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/LabelManualEdit`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/BudgetListScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/EnterBudgetScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/EditItemsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/MemberScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/../screens/SignupScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../screens/AddItemsScreen${`?${string}` | `#${string}` | ''}` | `/../screens/InventoryItemsScreen${`?${string}` | `#${string}` | ''}` | `/../screens/LabelManualEdit${`?${string}` | `#${string}` | ''}` | `/../screens/BudgetListScreen${`?${string}` | `#${string}` | ''}` | `/../screens/EnterBudgetScreen${`?${string}` | `#${string}` | ''}` | `/../screens/EditItemsScreen${`?${string}` | `#${string}` | ''}` | `/../screens/MemberScreen${`?${string}` | `#${string}` | ''}` | `/../screens/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/../screens/SignupScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/AddItemsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/InventoryItemsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/LabelManualEdit`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/BudgetListScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/EnterBudgetScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/EditItemsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/MemberScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/../screens/SignupScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
